services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    privileged: true
    expose:
      - 5432:5432
  memcached:
    image: memcached:latest
    restart: always
    expose:
      - 11211:11211
  backend:
    build: ./photonotes
    restart: always
    privileged: true
    volumes:
      - ./photonotes:/usr/local/photonotes
    expose:
      - 2087:2087
    command:
      # bash -c "
      # cd /usr/local/photonotes &&
      # python3 manage.py collectstatic --no-input --clear &&
      # python3 manage.py makemigrations && 
      # python3 manage.py migrate &&
      # python3 manage.py fill_test_users &&
      # python3 manage.py fill_db &&
      # python3 manage.py fill_site &&
      # gunicorn --bind :2087 --workers 2 PhotoNotes.wsgi:application"
      bash -c "
      cd /usr/local/photonotes &&
      python3 manage.py makemigrations && 
      python3 manage.py migrate &&
      gunicorn --bind :2087 --workers 2 PhotoNotes.wsgi:application"
    depends_on:
      - db
      - memcached
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./photonotes/static:/static
    ports:
      - 8443:8443
    depends_on:
      - backend
    environment:
      TZ: ${TIMEZONE}
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 443:443
    depends_on:
      - nginx
    environment:
      TZ: ${TIMEZONE}
