version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    privileged: true
    ports:
      - 5432:5432
  backend:
    build: ./photonotes
    restart: always
    privileged: true
    volumes:
      - ./data/media:/usr/local/photonotes/media
    #expose:
    ports:
      - 2087:2087
    command:
      #bash -c "
      #cd /usr/local/photonotes &&
      #python3 manage.py makemigrations && 
      #python3 manage.py migrate &&
      #python3 manage.py fill_test_users &&
      #python3 manage.py fill_db &&
      #gunicorn --bind :2087 --workers 2 PhotoNotes.wsgi:application"
      bash -c "
      cd /usr/local/photonotes &&
      python3 manage.py makemigrations && 
      python3 manage.py migrate &&
      gunicorn --bind :2087 --workers 2 PhotoNotes.wsgi:application"
    depends_on:
      - db
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 8443:8443
    depends_on:
      - backend
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 443:443
    depends_on:
      - nginx
